name: Sync Dev and Main Branches

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Sync branches
        run: |
          git checkout main
          git pull origin main
          git merge dev
          git push origin main

  auto-pass:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Auto pass on non-main branches
        run: echo "Auto pass on branch ${{ github.ref }}"
